### ISSUE TITLE
Thrift C-extensions causing exceptions in pycassa

### ISSUE THREAD

**Issue by banjoh** [pycassa/pycassa#245]
When using thrift v0.10.0 which includes some C-extensions (https://github.com/apache/thrift/tree/0.10.0/lib/py/src/ext), some functions in pycassa misbehave. How to reproduce

1. Running unit tests
```python
nosetests -vs tests/
ERROR

======================================================================
ERROR: test suite for <module 'tests' from '/home/mungev/repos/pycassa/tests/__init__.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mungev/repos/pycassa/venv_pycassa/local/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/home/mungev/repos/pycassa/venv_pycassa/local/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/home/mungev/repos/pycassa/venv_pycassa/local/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/home/mungev/repos/pycassa/venv_pycassa/local/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/mungev/repos/pycassa/tests/__init__.py", line 7, in setup_package
    if TEST_KS in sys.list_keyspaces():
  File "/home/mungev/repos/pycassa/pycassa/system_manager.py", line 121, in list_keyspaces
    return [ks.name for ks in self._conn.describe_keyspaces()]
  File "/home/mungev/repos/pycassa/pycassa/cassandra/Cassandra.py", line 1209, in describe_keyspaces
    return self.recv_describe_keyspaces()
  File "/home/mungev/repos/pycassa/pycassa/cassandra/Cassandra.py", line 1226, in recv_describe_keyspaces
    result.read(self._iprot)
  File "/home/mungev/repos/pycassa/pycassa/cassandra/Cassandra.py", line 6250, in read
    fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
AttributeError: 'TFramedTransport' object has no attribute 'trans'
-------------------- >> begin captured logging << --------------------
thrift.transport.sslcompat: WARNING: ipaddress module is unavailable
thrift.transport.sslcompat: WARNING: backports.ssl_match_hostname is unavailable
thrift.transport.sslcompat: DEBUG: ssl.match_hostname is available
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 0 tests in 0.004s

FAILED (errors=1)
```

2. Trying to use the library
```python
import pycassa
sm = pycassa.system_manager.SystemManager()
sm.list_keyspaces()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-643191200855> in <module>()
----> 1 sm.list_keyspaces()

/home/me/venv/lib/python2.7/site-packages/pycassa/system_manager.pyc in list_keyspaces(self)
    119     def list_keyspaces(self):
    120         """ Returns a list of all keyspace names. """
--> 121         return [ks.name for ks in self._conn.describe_keyspaces()]
    122 
    123     def describe_ring(self, keyspace):

/home/me/venv/lib/python2.7/site-packages/pycassa/cassandra/Cassandra.pyc in describe_keyspaces(self)
   1207     """
   1208     self.send_describe_keyspaces()
-> 1209     return self.recv_describe_keyspaces()
   1210 
   1211   def send_describe_keyspaces(self, ):

/home/me/venv/lib/python2.7/site-packages/pycassa/cassandra/Cassandra.pyc in recv_describe_keyspaces(self)
   1224       raise x
   1225     result = describe_keyspaces_result()
-> 1226     result.read(self._iprot)
   1227     self._iprot.readMessageEnd()
   1228     if result.success is not None:

/home/me/venv/lib/python2.7/site-packages/pycassa/cassandra/Cassandra.pyc in read(self, iprot)
   6248   def read(self, iprot):
   6249     if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
-> 6250       fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
   6251       return
   6252     iprot.readStructBegin()

AttributeError: 'TFramedTransport' object has no attribute 'trans'
```

Either downgrading to ```thrift v0.9.3``` or deleting the compiled C-extension binary from disk solves the problem

Some quick debugging led me to the code below which seems to be the culprit.
```python
fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
```
I found *84* matches of this line in https://github.com/pycassa/pycassa/blob/master/pycassa/cassandra/Cassandra.py.

**Comment by erebe** [comment]
same problem and same solution here

**Comment by nikhilo** [comment]
This helped me resolve the same error when connecting to remote cassandra host using pip installed cqlsh

**Comment by flokli** [comment]
Is this still broken in the latest release?

A lot of parts in `cassandra.py` seem autogenerated, maybe it's just an API change that needs to be done.
